/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiect.bd.pkgfinal;

/**
 *
 * @author Jamez-Laptop
 */


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class Examene extends javax.swing.JPanel {

    /**
     * Creates new form Examene
     */
    DefaultTableModel model;
    public Examene() {
        initComponents();
        
        model = (DefaultTableModel)jTable1.getModel();
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDExamen", "Nume", "Prenume", "Rezultat sala", "Rezultat traseu", "Data sala", "Data traseu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void update(){
    try {
            Connection cm = new Connection();
            
            ResultSet rs = cm.exQuery("SELECT * FROM Examen");
            
            //sterge rezultatele precedente
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            
            //nu afisez prima coloana
            TableColumn id=jTable1.getColumn("IDExamen");
            id.setMaxWidth(0);
            id.setMinWidth(0);
            id.setPreferredWidth(0);
            
            //populez tabelul
            while(rs.next()) {
                ResultSet ninst = cm.exQuery("SELECT * FROM Cursant WHERE IDCursant="+rs.getInt("IDCursant"));
                ninst.next();
                model.insertRow(model.getRowCount(),new Object[]{
                rs.getString("IDExamen"),ninst.getString("Nume"),ninst.getString("Prenume"),rs.getString("RezultatSala"),rs.getString("RezultatTraseu"),
                    rs.getString("Data_Sala"),rs.getString("Data_Oras")});
                cm.closeChannel(ninst);
            }
            cm.closeChannel(rs);
        } catch (SQLException ex) {
            Logger.getLogger(ProiectBDFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
     public int getId(){
        return Integer.parseInt((String) model.getValueAt(jTable1.getSelectedRow(), 0));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
