/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiect.bd.pkgfinal;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Jamez-Laptop
 */
public class Instructor extends javax.swing.JPanel {

    /**
     * Creates new form Instructor
     */
    DefaultTableModel model;
    
    public Instructor() {
        initComponents();
        
        model = (DefaultTableModel)jTable1.getModel();
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDInstructor", "Nume", "Prenume", "CNP", "DataNasterii", "Adresa", "Sex", "Categorie", "Salariu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
     public void update(){
        try {
            Connection cm = new Connection();
            
            ResultSet rs = cm.exQuery("SELECT * FROM Instructor");
            
            //sterge rezultatele precedente
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            
            //nu afisez primul camp
            TableColumn id = jTable1.getColumn("IDInstructor");
            id.setMaxWidth(0);
            id.setMinWidth(0);
            id.setPreferredWidth(0);
            
            //populez tabelul
            while(rs.next()) {
                model.insertRow(model.getRowCount(),new Object[]{
                rs.getString("IDInstructor"),rs.getString("Nume"),rs.getString("Prenume"),rs.getString("CNP"),
                    rs.getString("DataNasterii"),rs.getString("Adresa"),rs.getString("Sex"),rs.getString("Categorie"),rs.getString("Salariu")
                    });
            }
            cm.closeChannel(rs);
        } catch (SQLException ex) {
            Logger.getLogger(ProiectBDFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
     
     public int getId(){
        return Integer.parseInt((String) model.getValueAt(jTable1.getSelectedRow(), 0));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
