/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiect.bd.pkgfinal;

import javax.swing.JFrame;

/**
 *
 * @author Jamez-Laptop
 */
public class Interogari extends javax.swing.JPanel {

    /**
     * Creates new form Interogari
     */
    public Interogari() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        interog1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        interog2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        interog3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        interog4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        interog5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        interog6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        interog7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        interog8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        interog9 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        intero10 = new javax.swing.JButton();

        jLabel1.setText("Numarul de cursanti pentru fiecare instructor");

        interog1.setBackground(new java.awt.Color(153, 255, 153));
        interog1.setForeground(new java.awt.Color(0, 153, 51));
        interog1.setText("Executa");
        interog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interog1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Media kilometrilor parcursi de masinile instructorului cu numele Vasilut");

        interog2.setBackground(new java.awt.Color(153, 255, 153));
        interog2.setForeground(new java.awt.Color(0, 153, 51));
        interog2.setText("Executa");
        interog2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interog2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Numele si prenumele cursantilor care au instructorul cu numele Paul ");

        interog3.setBackground(new java.awt.Color(153, 255, 153));
        interog3.setForeground(new java.awt.Color(0, 153, 51));
        interog3.setText("Executa");
        interog3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interog3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Numele si prenumele cursantilor care au ore de condus in 2018");

        interog4.setBackground(new java.awt.Color(153, 255, 153));
        interog4.setForeground(new java.awt.Color(0, 153, 51));
        interog4.setText("Executa");
        interog4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interog4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Numele si prenumele instructorilor mai batrani de 50 ani care au avut ore pe motocicleta Yamaha");

        interog5.setBackground(new java.awt.Color(153, 255, 153));
        interog5.setForeground(new java.awt.Color(0, 153, 51));
        interog5.setText("Executa");
        interog5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interog5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Interogari simple");

        jLabel7.setText("Numele, prenumele, categoria si de cate ori au fost programati la ore de condus in anul 2018");

        interog6.setBackground(new java.awt.Color(153, 255, 153));
        interog6.setForeground(new java.awt.Color(0, 153, 51));
        interog6.setText("Executa");
        interog6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interog6ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Interogari Complexe");

        jLabel9.setText("Numele, Prenumele si Salariul instructorilor cu salariul sub medie");

        interog7.setBackground(interog3.getBackground());
        interog7.setForeground(interog1.getForeground());
        interog7.setText("Executa");
        interog7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interog7ActionPerformed(evt);
            }
        });

        jLabel10.setText("Numele si Prenumele instructorilor cu cursanti care au promovat examenul");

        interog8.setBackground(interog3.getBackground());
        interog8.setForeground(interog1.getForeground());
        interog8.setText("Executa");
        interog8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interog8ActionPerformed(evt);
            }
        });

        jLabel11.setText("Anii in care au fost admisi cei mai multi cursanti");

        interog9.setBackground(interog3.getBackground());
        interog9.setForeground(interog1.getForeground());
        interog9.setText("Executa");
        interog9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interog9ActionPerformed(evt);
            }
        });

        jLabel12.setText("Numele si prenumele cursantului cu cele mai multe ore");

        intero10.setBackground(interog3.getBackground());
        intero10.setForeground(interog1.getForeground());
        intero10.setText("Executa");
        intero10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intero10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(interog1)
                    .addComponent(jLabel2)
                    .addComponent(interog2)
                    .addComponent(jLabel3)
                    .addComponent(interog3)
                    .addComponent(jLabel4)
                    .addComponent(interog4)
                    .addComponent(jLabel5)
                    .addComponent(interog5)
                    .addComponent(jLabel7)
                    .addComponent(interog6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interog7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(interog8)
                    .addComponent(jLabel11)
                    .addComponent(interog9)
                    .addComponent(jLabel12)
                    .addComponent(intero10))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interog1)
                    .addComponent(interog7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interog2)
                    .addComponent(interog8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interog3)
                    .addComponent(interog9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interog4)
                    .addComponent(intero10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interog5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interog6)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void interog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interog1ActionPerformed
        JFrame inter1 = new Interog1();
        inter1.setVisible(true);
        inter1.setTitle("Interogare");
        inter1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_interog1ActionPerformed

    private void interog2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interog2ActionPerformed
        JFrame inter2 = new Interog2();
        inter2.setVisible(true);
        inter2.setTitle("Interogare");
        inter2.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_interog2ActionPerformed

    private void interog3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interog3ActionPerformed
        JFrame inter3 = new Interog3();
        inter3.setVisible(true);
        inter3.setTitle("Interogare");
        inter3.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_interog3ActionPerformed

    private void interog4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interog4ActionPerformed
        JFrame inter3 = new Interog4();
        inter3.setVisible(true);
        inter3.setTitle("Interogare");
        inter3.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_interog4ActionPerformed

    private void interog5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interog5ActionPerformed
        JFrame inter3 = new Interog5();
        inter3.setVisible(true);
        inter3.setTitle("Interogare");
        inter3.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_interog5ActionPerformed

    private void interog6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interog6ActionPerformed
        JFrame inter3 = new Interog6();
        inter3.setVisible(true);
        inter3.setTitle("Interogare");
        inter3.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_interog6ActionPerformed

    private void interog7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interog7ActionPerformed
        JFrame inter3 = new Interog7();
        inter3.setVisible(true);
        inter3.setTitle("Interogare");
        inter3.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_interog7ActionPerformed

    private void interog8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interog8ActionPerformed
        JFrame inter3 = new Interog8();
        inter3.setVisible(true);
        inter3.setTitle("Interogare");
        inter3.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_interog8ActionPerformed

    private void interog9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interog9ActionPerformed
        JFrame inter3 = new Interog9();
        inter3.setVisible(true);
        inter3.setTitle("Interogare");
        inter3.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_interog9ActionPerformed

    private void intero10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intero10ActionPerformed
        JFrame inter3 = new Interog10();
        inter3.setVisible(true);
        inter3.setTitle("Interogare");
        inter3.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_intero10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton intero10;
    private javax.swing.JButton interog1;
    private javax.swing.JButton interog2;
    private javax.swing.JButton interog3;
    private javax.swing.JButton interog4;
    private javax.swing.JButton interog5;
    private javax.swing.JButton interog6;
    private javax.swing.JButton interog7;
    private javax.swing.JButton interog8;
    private javax.swing.JButton interog9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
